Web1001Todo/Models/ErrorViewModel.cs
namespace Web1001Todo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web1001Todo/Models/Todo.cs
namespace Web1001Todo.Models
{
    public class Todo
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public bool IsComplete { get; set; }
        public DateTime? CompleteDate { get; set; }
    }
}

Web1001Todo/Models/TodoDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Web1001Todo.Models
{
    public class TodoDbContext : DbContext
    {
        public TodoDbContext(DbContextOptions<TodoDbContext> options) : base(options)
        {

        }

        public DbSet<Todo> Todos { get; set; }
    }
}

Web1001Todo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web1001Todo.Models;

namespace Web1001Todo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web1001Todo/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web1001Todo.Models;

namespace Web1001Todo.Controllers
{
    public class TodoController : Controller
    {
        private readonly TodoDbContext _context;

        public TodoController(TodoDbContext context)
        {
            _context = context;
        }

        // GET: Todo
        public async Task<IActionResult> Index()
        {
              return View(await _context.Todos.Where(t => !t.IsComplete).ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> MarkCompletedTodos()
        {
            return View(await _context.Todos.Where(t => t.IsComplete).ToListAsync());
        }

        // GET: Todo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Todos == null)
            {
                return NotFound();
            }

            var todo = await _context.Todos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (todo == null)
            {
                return NotFound();
            }

            return View(todo);
        }

        // GET: Todo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Todo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Details,IsComplete,CompleteDate")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(todo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(todo);
        }

        // GET: Todo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Todos == null)
            {
                return NotFound();
            }

            var todo = await _context.Todos.FindAsync(id);
            if (todo == null)
            {
                return NotFound();
            }
            return View(todo);
        }

        // POST: Todo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Details,IsComplete,CompleteDate")] Todo todo)
        {
            if (id != todo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(todo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TodoExists(todo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(todo);
        }

        // GET: Todo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Todos == null)
            {
                return NotFound();
            }

            var todo = await _context.Todos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (todo == null)
            {
                return NotFound();
            }

            return View(todo);
        }

        // POST: Todo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Todos == null)
            {
                return Problem("Entity set 'TodoDbContext.Todos'  is null.");
            }
            var todo = await _context.Todos.FindAsync(id);
            if (todo != null)
            {
                _context.Todos.Remove(todo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TodoExists(int id)
        {
          return _context.Todos.Any(e => e.Id == id);
        }
    }
}

Web1001Todo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web1001Todo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web1001Todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web1001Todo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web1001Todo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="todo" asp-action="Index">Todo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="todo" asp-action="MarkCompletedTodos">Completed Todos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web1001Todo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web1001Todo/Views/Todo/Create.cshtml
@model Todo

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-12">
        <h3 class="text-center">Create Todo</h3>
        <hr />
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-body">
                <form class="row g-3" method="post" asp-action="create" asp-controller="Todo">
                    <div class="col-md-12">
                        <label class="form-label" asp-for="Title">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label" asp-for="Details">Details</label>
                        <textarea class="form-control" asp-for="Details"></textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-success">Save</button>
                        <a class="btn btn-info" asp-action="index" asp-controller="todo">Back To List</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Web1001Todo/Views/Todo/Delete.cshtml
@model Web1001Todo.Models.Todo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompleteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompleteDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web1001Todo/Views/Todo/Details.cshtml
@model Web1001Todo.Models.Todo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsComplete)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompleteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompleteDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web1001Todo/Views/Todo/Edit.cshtml
@model Todo

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-12">
        <h3 class="text-center">Edit Todo</h3>
        <hr />
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-body">
                <form class="row g-3" method="post" asp-action="edit" asp-controller="Todo">
                    <div class="col-md-12">
                        <label class="form-label" asp-for="Title">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label" asp-for="Details">Details</label>
                        <textarea class="form-control" asp-for="Details"></textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 mt-5">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" asp-for="IsComplete">
                            <label class="form-check-label" asp-for="IsComplete">
                                Complete
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label" asp-for="CompleteDate">Complete Date</label>
                        <input type="date" class="form-control" asp-for="CompleteDate"></input>
                        <span asp-validation-for="CompleteDate" class="text-danger"></span>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-success">Update</button>
                        <a class="btn btn-info" asp-action="index" asp-controller="todo">Back To List</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Web1001Todo/Views/Todo/Index.cshtml
@model IEnumerable<Todo>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-12">
        <h3 class="text-center">Incomplete Todos</h3>
        <hr />
        <a asp-action="create" asp-controller="todo" class="btn btn-primary">Add Todo</a>
    </div>
</div>
<div class="row justify-content-center mt-3">
    <div class="col-md-10">
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Details</th>
                    <th>Complete Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var todo in Model)
                {
                    <tr>
                        <td>@todo.Title</td>
                        <td>@todo.Details</td>
                        <td>
                            @if (todo.IsComplete == false)
                            {
                                <span>Incomplete</span>
                            }
                        </td>
                        <td>
                            <a asp-action="edit" asp-controller="todo" asp-route-id="@todo.Id" class="btn btn-info">Edit</a>
                            <a asp-action="delete" asp-controller="todo" asp-route-id="@todo.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Web1001Todo/Views/Todo/MarkCompletedTodos.cshtml
@model IEnumerable<Todo>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-12">
        <h3 class="text-center">Complete Todos</h3>
        <hr />
        <a asp-action="create" asp-controller="todo" class="btn btn-primary">Add Todo</a>
    </div>
</div>
<div class="row justify-content-center mt-3">
    <div class="col-md-10">
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Details</th>
                    <th>Complete Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var todo in Model)
                {
                    <tr>
                        <td>@todo.Title</td>
                        <td>@todo.Details</td>
                        <td>
                            @if (todo.IsComplete == false)
                            {
                                <span>Incomplete</span>
                            }
                            else
                            {
                                <span>Complete</span>
                            }
                        </td>
                        <td>
                            <a asp-action="delete" asp-controller="todo" asp-route-id="@todo.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>